### ISSUE TITLE
How can I use the HOST_GROUP or –-set-host-group parameter.

### ISSUE THREAD

**Issue by organic-scholar** [Dynatrace/heroku-buildpack-dynatrace#18]
I need to group host the option is to pass --set-host-group parameter to installer.

https://www.dynatrace.com/support/help/how-to-use-dynatrace/hosts/configuration/organize-your-environment-using-host-groups/

need some help on this

**Comment by arthfl** [comment]
Hi @organic-scholar,
sorry for the late answer on this.

You can use the network-zones feature for that:https://www.dynatrace.com/support/help/shortlink/heroku#-optional-configure-network-zones

**Comment by avdveen** [comment]
Getting a warning that DT_HOST_ID is required when trying to add the agent on Heroku 18. The docs do not reference the need for this. The URL that needs to be used is also not clear from the docs. Since it is Heroku 18, we need to use v1.0 if I understand correctly. Should the URL be https://github.com/Dynatrace/heroku-buildpack-dynatrace.git#v1.0? We tried is as is, but it complains it cannot find the buildpack. Using the URL without #<version> allows the build to complete, but the agent never shows up in the tenant. We've double-checked the tenant ID and API token.
